[package]
name = "turinglike-oversophisticated-calculator"
version = "0.1.0"
authors = ["mbalc <mbalc909@gmail.com>"]
edition = "2018"

[[bin]]
name = "interpreter"
path = "src/interpreter.rs"

[build-dependencies]
clippy = { version = "*", optional = true }

[dependencies]
